Flask/django_animalai/aiapps/aiapps/urls.py
from django.contrib import admin
from django.urls import path
# import animalai.views as animalai
from django.urls import include
# urls.pyを読むように追加
urlpatterns = [
    path('admin/', admin.site.urls),
    path('animalai/', include('animalai.urls')),
]

# path('animalai/', animalai.index),

Flask/django_animalai/aiapps/animalai/urls.py
from django.urls import path
from . import views
app_name = 'animalai'
urlpatterns = [
    path('', views.index, name='index'),
    path('predict/', views.predict, name='predict'),
]

Flask/django_animalai/aiapps/animalai/models.py
from django.db import models

import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.models import load_model
from PIL import Image
import io, base64 # 


graph = tf.compat.v1.get_default_graph()

class Photo(models.Model):
    image = models.ImageField(upload_to='photos')

    IMAGE_SIZE = 50
    MODEL_FILE_PATH = './animalai/ml_models/animal_cnn.h5'

    classes = ["monkey", "boar", "crow"]
    num_classes = len(classes)

    def predict(self):
        model = None
        global graph
        # モデル読み込み
        with graph.as_default():
            model = load_model(self.MODEL_FILE_PATH)

            img_data = self.image.read()
            img_bin = io.BytesIO(img_data) # データをメモリ上に保管してファイルのようにアクセスする

            image = Image.open(img_bin)
            image = image.convert('RGB') # Grayscaleの場合もカラーに変換
            image = image.resize((self.IMAGE_SIZE, self.IMAGE_SIZE))
            data = np.asarray(image)
            X = []
            X.append(data)
            X = np.asarray(X)

            result = model.predict([X])[0]
            predicted = result.argmax()
            percentage = int(result[predicted] * 100)
            print("{0}({1} %)".format(self.classes[predicted], percentage))

            return self.classes[predicted], percentage
    
    def image_src(self):
        with self.image.open() as img:
            base64_img = base64.b64encode(img.read()).decode()

            return 'data:' + img.file.content_type + ';base64,' + base64_img

Flask/django_animalai/aiapps/animalai/forms.py
from django import forms

class PhotoForm(forms.Form):
    image = forms.ImageField(widget=forms.FileInput(attrs={'class':'custom-file-input'}))

Flask/django_animalai/aiapps/animalai/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.template import loader
from .forms import PhotoForm
from .models import Photo

# index.htmlを返す
def index(request):
    # テンプレートを読み込んで変数にセット
    template = loader.get_template('animalai/index.html')
    context = {'form':PhotoForm()}
    # return HttpResponse("Hello World!")
    return HttpResponse(template.render(context, request))

def predict(request):
    # データが送られてきたか確認する
    if not request.method == 'POST':
        return redirect('animalai:index')
    
    form = PhotoForm(request.POST, request.FILES)
    # 有効なデータだと先に進む
    if not form.is_valid():
        raise ValueError('Formが不正です')

    photo = Photo(image=form.cleaned_data['image'])
    # 返り値を受け取る
    predicted, percentage = photo.predict()
    template = loader.get_template('animalai/result.html')
    context = {
        "photo_data": photo.image_src(),
        "photo_name":photo.image.name,
        "predicted":predicted,
        "percentage":percentage,}
    return HttpResponse(template.render(context, request))

    # return HttpResponse("Show predictions")

Flask/django_animalai/aiapps/animalai/templates/animalai/base.html
<!DOCTYPE html>
<html lang='ja'>
<head>
    <meta charset="UTF-8">
    <!-- Bootstrap4を活用 -->
    {% load static %}
    {% load bootstrap4 %} 
    {% bootstrap_css %} 
    <link rel="stylesheet" type="text/css" href="{% static 'animalai/css/style.css' %}">
    {% bootstrap_javascript jquery='full' %}
    <title>判定 | {% block title %}{% endblock %}</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#">画像判定AIアプリ</a>
    </nav>
    <div class="containter">
        {% block content %}{% endblock %}
    </div>
</body>
</html>

Flask/django_animalai/aiapps/animalai/templates/animalai/index.html
<!-- base.htmlを拡張する -->
{% extends 'animalai/base.html' %} 
{% block title %}推定アプリメニュー{% endblock %}
{% block content %} 
<div>
    <h4 class="mt-4 mb-5 border-bottom">推定アプリ</h4>
    <p>画像ファイルを選択して推定ボタンをクリックしてください。</div></p>
    <!-- animalaiのpredict関数に移動する -->
    <form action="{% url 'animalai:predict' %}" method="post" class="form" enctype="multipart/form-data">
        <!-- フォームに外部プログラムからデータを送り付ける攻撃を防ぐ -->
        {% csrf_token %}
    <div class="form-group">
        <div class="custom-file">
            {{ form.image }}
            <label class="custom-file-label" for="customFile">
                推定したいファイルを選択してください
            </label>
        </div>
    </div>
    <button type="submit" class="btn btn-primary">推定する</button>
    </form>
</div>
{% endblock %}

Flask/django_animalai/aiapps/animalai/templates/animalai/result.html
{% extends 'animalai/base.html' %} 
{% block title %}推定結果{% endblock %}
{% block content %} 
<div>
    <h4 class="mt-4 mb-5 border-bottom">推定結果</h4>

    <table class='table'>
        <tbody>
            <tr>
                <td>ファイル名</td>
                <td>{{ photo_name }}</td>
            </tr>
            <tr>
                <td>画像ファイル</td>
                <td><img class='preview-img' src={{ photo_data }}></img></td>
            </tr>
            <tr>
                <td>推定ラベル</td>
                <td>{{ predicted }}</td>
            </tr>
            <tr>
                <td>推定確率</td>
                <td>{{ percentage }} %</td>
            </tr>
        </tbody>
    </table>

    <a href = "{% url 'animalai:index' %}" class="btn btn-primary">画像選択メニューに戻る</a>
</div>

{% endblock %}